// Auto-generated on 2024-12-20T12:00:00.000Z
// DO NOT EDIT MANUALLY - This file is generated by scripts/fetch-data.ts

export const adultSocialCare = {
  totalRecipients: 875000,
  bySupportType: [
    { category: 'Community care', value: 610000, percentage: 69.7 },
    { category: 'Residential care', value: 165000, percentage: 18.9 },
    { category: 'Nursing care', value: 100000, percentage: 11.4 },
  ],
  byAge: [
    { category: '18-64', value: 280000, percentage: 32.0 },
    { category: '65-74', value: 130000, percentage: 14.9 },
    { category: '75-84', value: 210000, percentage: 24.0 },
    { category: '85+', value: 255000, percentage: 29.1 },
  ],
  byPrimarySupportReason: [
    { category: 'Physical support', value: 420000, percentage: 48.0 },
    { category: 'Support with memory and cognition', value: 145000, percentage: 16.6 },
    { category: 'Learning disability support', value: 125000, percentage: 14.3 },
    { category: 'Mental health support', value: 85000, percentage: 9.7 },
    { category: 'Social support', value: 70000, percentage: 8.0 },
    { category: 'Sensory support', value: 30000, percentage: 3.4 },
  ],
  expenditure: 22100000000,
  newRequestsForSupport: 1850000,
  timeSeries: [
    { date: '2019-20', value: 890000 },
    { date: '2020-21', value: 820000 },
    { date: '2021-22', value: 850000 },
    { date: '2022-23', value: 860000 },
    { date: '2023-24', value: 875000 },
  ],
  workforce: {
    totalJobs: 1770000,
    vacancies: 152000,
    vacancyRate: 8.6,
    turnoverRate: 28.3,
  },
  source: {
    name: 'DHSC Adult Social Care Statistics',
    url: 'https://www.gov.uk/government/collections/adult-social-care-statistics',
    releaseDate: 'November 2024',
  },
} as const;
