// Auto-generated on 2026-03-17T04:23:29.553Z
// DO NOT EDIT MANUALLY - This file is generated by scripts/fetch-data.ts

export const asylumSupport = {
  "section95": {
    "inPayment": 102000,
    "inAccommodation": 56000,
    "byNationality": [
      {
        "category": "Afghanistan",
        "value": 28000,
        "percentage": 27.5
      },
      {
        "category": "Iran",
        "value": 14000,
        "percentage": 13.7
      },
      {
        "category": "Syria",
        "value": 11000,
        "percentage": 10.8
      },
      {
        "category": "Sudan",
        "value": 9000,
        "percentage": 8.8
      },
      {
        "category": "Eritrea",
        "value": 8000,
        "percentage": 7.8
      },
      {
        "category": "Iraq",
        "value": 7000,
        "percentage": 6.9
      },
      {
        "category": "Albania",
        "value": 5000,
        "percentage": 4.9
      },
      {
        "category": "Vietnam",
        "value": 4000,
        "percentage": 3.9
      },
      {
        "category": "Other",
        "value": 16000,
        "percentage": 15.7
      }
    ],
    "byAccommodationType": [
      {
        "category": "Dispersed accommodation",
        "value": 38000,
        "percentage": 67.9
      },
      {
        "category": "Self-catered accommodation",
        "value": 12000,
        "percentage": 21.4
      },
      {
        "category": "Full-board accommodation",
        "value": 6000,
        "percentage": 10.7
      }
    ],
    "dailyAllowance": {
      "singleAdult": 6.77,
      "couple": 9.42,
      "singleParent16plus": 6.77,
      "child16to17": 5.08,
      "childUnder16": 3.95
    }
  },
  "section4": {
    "totalCaseload": 4500,
    "byNationality": [
      {
        "category": "Iran",
        "value": 1100,
        "percentage": 24.4
      },
      {
        "category": "Iraq",
        "value": 800,
        "percentage": 17.8
      },
      {
        "category": "Sudan",
        "value": 600,
        "percentage": 13.3
      },
      {
        "category": "Other",
        "value": 2000,
        "percentage": 44.4
      }
    ]
  },
  "hotels": {
    "totalInHotels": 38000,
    "byRegion": [
      {
        "region": "London",
        "value": 7500
      },
      {
        "region": "South East",
        "value": 6000
      },
      {
        "region": "North West",
        "value": 5500
      },
      {
        "region": "Yorkshire and Humber",
        "value": 4500
      },
      {
        "region": "West Midlands",
        "value": 4000
      },
      {
        "region": "East Midlands",
        "value": 3500
      },
      {
        "region": "North East",
        "value": 3000
      },
      {
        "region": "South West",
        "value": 2500
      },
      {
        "region": "East of England",
        "value": 1500
      }
    ],
    "averageStayDays": 140,
    "dailyCostPerPerson": 130
  },
  "unaccompaniedChildren": {
    "total": 6700,
    "byAge": [
      {
        "category": "Under 14",
        "value": 400,
        "percentage": 6
      },
      {
        "category": "14-15",
        "value": 1600,
        "percentage": 23.9
      },
      {
        "category": "16-17",
        "value": 4700,
        "percentage": 70.1
      }
    ],
    "byNationality": [
      {
        "category": "Afghanistan",
        "value": 2300,
        "percentage": 34.3
      },
      {
        "category": "Sudan",
        "value": 1200,
        "percentage": 17.9
      },
      {
        "category": "Albania",
        "value": 900,
        "percentage": 13.4
      },
      {
        "category": "Eritrea",
        "value": 800,
        "percentage": 11.9
      },
      {
        "category": "Other",
        "value": 1500,
        "percentage": 22.4
      }
    ]
  },
  "timeSeries": [
    {
      "date": "2019-Q4",
      "value": 42000
    },
    {
      "date": "2020-Q4",
      "value": 45000
    },
    {
      "date": "2021-Q4",
      "value": 58000
    },
    {
      "date": "2022-Q4",
      "value": 85000
    },
    {
      "date": "2023-Q4",
      "value": 95000
    },
    {
      "date": "2024-Q3",
      "value": 102000
    }
  ],
  "source": {
    "name": "Home Office Immigration Statistics",
    "url": "https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables",
    "releaseDate": "November 2024"
  }
} as const;
