// Auto-generated on 2026-04-03T04:34:24.320Z
// DO NOT EDIT MANUALLY - This file is generated by scripts/fetch-data.ts

export const carers = {
  "carersAllowance": {
    "totalCaseload": 1450000,
    "changeYoY": 5.2,
    "byAge": [
      {
        "category": "Under 25",
        "value": 120000,
        "percentage": 8.3
      },
      {
        "category": "25-34",
        "value": 220000,
        "percentage": 15.2
      },
      {
        "category": "35-44",
        "value": 280000,
        "percentage": 19.3
      },
      {
        "category": "45-54",
        "value": 350000,
        "percentage": 24.1
      },
      {
        "category": "55-64",
        "value": 380000,
        "percentage": 26.2
      },
      {
        "category": "65+",
        "value": 100000,
        "percentage": 6.9
      }
    ],
    "byGender": [
      {
        "category": "Female",
        "value": 980000,
        "percentage": 67.6
      },
      {
        "category": "Male",
        "value": 470000,
        "percentage": 32.4
      }
    ],
    "averageWeeklyAward": 81.9
  },
  "carerElementUC": {
    "total": 890000,
    "averageWeeklyAward": 198.31
  },
  "unpaidCarersEstimate": 5.7,
  "byHoursCared": [
    {
      "category": "Under 20 hours",
      "value": 2100000,
      "percentage": 36.8
    },
    {
      "category": "20-34 hours",
      "value": 700000,
      "percentage": 12.3
    },
    {
      "category": "35-49 hours",
      "value": 500000,
      "percentage": 8.8
    },
    {
      "category": "50+ hours",
      "value": 2400000,
      "percentage": 42.1
    }
  ],
  "byHealthOfCaredFor": [
    {
      "category": "Physical disability",
      "value": 2400000,
      "percentage": 42.1
    },
    {
      "category": "Mental health condition",
      "value": 850000,
      "percentage": 14.9
    },
    {
      "category": "Dementia/Alzheimer's",
      "value": 680000,
      "percentage": 11.9
    },
    {
      "category": "Learning disability",
      "value": 520000,
      "percentage": 9.1
    },
    {
      "category": "Old age/frailty",
      "value": 480000,
      "percentage": 8.4
    },
    {
      "category": "Other",
      "value": 780000,
      "percentage": 13.7
    }
  ],
  "timeSeries": [
    {
      "date": "2019",
      "value": 1180000,
      "note": "Carer's Allowance"
    },
    {
      "date": "2020",
      "value": 1220000,
      "note": "Carer's Allowance"
    },
    {
      "date": "2021",
      "value": 1280000,
      "note": "Carer's Allowance"
    },
    {
      "date": "2022",
      "value": 1340000,
      "note": "Carer's Allowance"
    },
    {
      "date": "2023",
      "value": 1380000,
      "note": "Carer's Allowance"
    },
    {
      "date": "2024",
      "value": 1450000,
      "note": "Carer's Allowance"
    }
  ],
  "source": {
    "name": "DWP Carer Statistics",
    "url": "https://www.gov.uk/government/collections/carers-allowance-and-carers-credit-statistics",
    "releaseDate": "November 2024"
  }
} as const;
