// Auto-generated on 2026-06-05T06:37:16.951Z
// DO NOT EDIT MANUALLY - This file is generated by scripts/fetch-data.ts

export const childBenefit = {
  "totalCaseload": 7.1,
  "childrenCovered": 12.5,
  "byRegion": [
    {
      "region": "London",
      "value": 1.1,
      "note": "million families"
    },
    {
      "region": "South East",
      "value": 0.95,
      "note": "million families"
    },
    {
      "region": "North West",
      "value": 0.85,
      "note": "million families"
    },
    {
      "region": "East of England",
      "value": 0.65,
      "note": "million families"
    },
    {
      "region": "West Midlands",
      "value": 0.6,
      "note": "million families"
    },
    {
      "region": "Yorkshire and Humber",
      "value": 0.55,
      "note": "million families"
    },
    {
      "region": "South West",
      "value": 0.52,
      "note": "million families"
    },
    {
      "region": "East Midlands",
      "value": 0.45,
      "note": "million families"
    },
    {
      "region": "North East",
      "value": 0.3,
      "note": "million families"
    },
    {
      "region": "Scotland",
      "value": 0.52,
      "note": "million families"
    },
    {
      "region": "Wales",
      "value": 0.32,
      "note": "million families"
    },
    {
      "region": "Northern Ireland",
      "value": 0.28,
      "note": "million families"
    }
  ],
  "weeklyRates": {
    "eldestOrOnlyChild": 26.05,
    "additionalChildren": 17.25,
    "guardianAllowance": 18.55
  },
  "annualExpenditure": 11700000000,
  "highIncomeChargeCases": 850000,
  "timeSeries": [
    {
      "date": "2019",
      "value": 7.8,
      "note": "million families"
    },
    {
      "date": "2020",
      "value": 7.7,
      "note": "million families"
    },
    {
      "date": "2021",
      "value": 7.5,
      "note": "million families"
    },
    {
      "date": "2022",
      "value": 7.4,
      "note": "million families"
    },
    {
      "date": "2023",
      "value": 7.2,
      "note": "million families"
    },
    {
      "date": "2024",
      "value": 7.1,
      "note": "million families"
    }
  ],
  "source": {
    "name": "HMRC Child Benefit Statistics",
    "url": "https://www.gov.uk/government/collections/child-benefit-statistics",
    "releaseDate": "August 2024"
  }
} as const;
