// Auto-generated on 2026-05-14T05:52:30.199Z
// DO NOT EDIT MANUALLY - This file is generated by scripts/fetch-data.ts

export const devolvedNations = {
  "scotland": {
    "adultDisabilityPayment": {
      "totalCaseload": 245000,
      "newAwards": 85000,
      "averageAward": 72.5
    },
    "carerAllowanceSupplement": {
      "recipients": 135000,
      "biannualPayment": 288.6
    },
    "bestStartGrants": {
      "totalPayments": 125000,
      "expenditure": 28000000
    },
    "scottishChildPayment": {
      "recipients": 325000,
      "weeklyRate": 26.7,
      "expenditure": 450000000
    },
    "pensionAgeDisabilityPayment": {
      "totalCaseload": 52000
    },
    "source": {
      "name": "Social Security Scotland",
      "url": "https://www.socialsecurity.gov.scot/about-statistics",
      "releaseDate": "November 2024"
    }
  },
  "wales": {
    "notes": "Wales does not have significant devolved welfare powers. Most benefits are administered by DWP UK-wide. Welsh Government provides discretionary assistance via the Discretionary Assistance Fund.",
    "discretionaryAssistanceFund": {
      "totalAwards": 85000,
      "totalExpenditure": 12500000
    },
    "source": {
      "name": "Welsh Government",
      "url": "https://gov.wales/discretionary-assistance-fund",
      "releaseDate": "2024"
    }
  },
  "northernIreland": {
    "notes": "Northern Ireland has some devolved social security powers but generally mirrors GB system. Universal Credit is administered by DWP.",
    "universalCredit": {
      "caseload": 230000
    },
    "employmentSupportAllowance": {
      "caseload": 55000
    },
    "source": {
      "name": "Northern Ireland Department for Communities",
      "url": "https://www.communities-ni.gov.uk/",
      "releaseDate": "2024"
    }
  }
} as const;
