// Auto-generated on 2026-05-01T05:46:31.383Z
// DO NOT EDIT MANUALLY - This file is generated by scripts/fetch-data.ts

export const dla = {
  "totalCaseload": 990000,
  "changeYoY": -5.2,
  "byAge": [
    {
      "category": "Under 16",
      "value": 420000,
      "percentage": 42.4
    },
    {
      "category": "16-64",
      "value": 310000,
      "percentage": 31.3
    },
    {
      "category": "65+",
      "value": 260000,
      "percentage": 26.3
    }
  ],
  "byRegion": [
    {
      "region": "North East",
      "value": 70000,
      "percentage": 2.6
    },
    {
      "region": "North West",
      "value": 150000,
      "percentage": 2.1
    },
    {
      "region": "Yorkshire and Humber",
      "value": 90000,
      "percentage": 1.6
    },
    {
      "region": "East Midlands",
      "value": 70000,
      "percentage": 1.4
    },
    {
      "region": "West Midlands",
      "value": 100000,
      "percentage": 1.7
    },
    {
      "region": "East of England",
      "value": 80000,
      "percentage": 1.3
    },
    {
      "region": "London",
      "value": 80000,
      "percentage": 0.9
    },
    {
      "region": "South East",
      "value": 130000,
      "percentage": 1.4
    },
    {
      "region": "South West",
      "value": 90000,
      "percentage": 1.5
    },
    {
      "region": "Wales",
      "value": 70000,
      "percentage": 2.2
    },
    {
      "region": "Scotland",
      "value": 120000,
      "percentage": 2.3
    },
    {
      "region": "Northern Ireland",
      "value": 50000,
      "percentage": 2.7
    }
  ],
  "source": {
    "name": "DWP DLA Statistics",
    "url": "https://www.gov.uk/government/collections/disability-living-allowance-dla-statistics",
    "releaseDate": "November 2024"
  }
} as const;
