// Auto-generated on 2026-06-10T06:36:38.723Z
// DO NOT EDIT MANUALLY - This file is generated by scripts/fetch-data.ts

export const esa = {
  "totalCaseload": 1520000,
  "changeYoY": -3.1,
  "byType": [
    {
      "category": "Contributory ESA",
      "value": 680000,
      "percentage": 44.7
    },
    {
      "category": "Income-related ESA",
      "value": 840000,
      "percentage": 55.3
    }
  ],
  "byGroup": [
    {
      "category": "Work-Related Activity Group",
      "value": 420000,
      "percentage": 27.6
    },
    {
      "category": "Support Group",
      "value": 1100000,
      "percentage": 72.4
    }
  ],
  "byCondition": [
    {
      "category": "Mental and behavioural disorders",
      "value": 680000,
      "percentage": 44.7
    },
    {
      "category": "Diseases of the musculoskeletal system",
      "value": 230000,
      "percentage": 15.1
    },
    {
      "category": "Diseases of the nervous system",
      "value": 140000,
      "percentage": 9.2
    },
    {
      "category": "Diseases of the circulatory system",
      "value": 86000,
      "percentage": 5.7
    },
    {
      "category": "Other",
      "value": 384000,
      "percentage": 25.3
    }
  ],
  "timeSeries": [
    {
      "date": "2019-01",
      "value": 2100000
    },
    {
      "date": "2020-01",
      "value": 2000000
    },
    {
      "date": "2021-01",
      "value": 1850000
    },
    {
      "date": "2022-01",
      "value": 1750000
    },
    {
      "date": "2023-01",
      "value": 1620000
    },
    {
      "date": "2024-01",
      "value": 1520000
    }
  ],
  "source": {
    "name": "DWP ESA Statistics",
    "url": "https://www.gov.uk/government/collections/employment-and-support-allowance-esa-statistics",
    "releaseDate": "November 2024"
  }
} as const;
