// Auto-generated on 2026-04-22T04:50:27.790Z
// DO NOT EDIT MANUALLY - This file is generated by scripts/fetch-data.ts

export const headline = {
  "totalBenefitClaimants": 22.4,
  "universalCredit": 6420000,
  "pipCaseload": 3670000,
  "asylumSupport": 102000,
  "peopleInPoverty": 14.5,
  "householdsHomeless": 117000,
  "unpaidCarers": 5.7,
  "annualWelfareExpenditure": 295000000000,
  "lastUpdated": "2026-04-22T04:50:27.790Z"
} as const;
