// Auto-generated on 2026-04-17T04:53:09.023Z
// DO NOT EDIT MANUALLY - This file is generated by scripts/fetch-data.ts

export const homelessness = {
  "totalHouseholds": 324000,
  "inTemporaryAccommodation": 117000,
  "roughSleeping": 4389,
  "byReason": [
    {
      "category": "End of private rented tenancy",
      "value": 32000,
      "percentage": 24.6
    },
    {
      "category": "Friends/family no longer able to accommodate",
      "value": 27000,
      "percentage": 20.8
    },
    {
      "category": "Domestic abuse",
      "value": 22000,
      "percentage": 16.9
    },
    {
      "category": "Non-violent relationship breakdown",
      "value": 15000,
      "percentage": 11.5
    },
    {
      "category": "Other reasons",
      "value": 34000,
      "percentage": 26.2
    }
  ],
  "byRegion": [
    {
      "region": "London",
      "value": 63000,
      "percentage": 53.8
    },
    {
      "region": "South East",
      "value": 14000,
      "percentage": 12
    },
    {
      "region": "North West",
      "value": 10000,
      "percentage": 8.5
    },
    {
      "region": "East of England",
      "value": 8000,
      "percentage": 6.8
    },
    {
      "region": "South West",
      "value": 7000,
      "percentage": 6
    },
    {
      "region": "West Midlands",
      "value": 6000,
      "percentage": 5.1
    },
    {
      "region": "Yorkshire and Humber",
      "value": 5000,
      "percentage": 4.3
    },
    {
      "region": "East Midlands",
      "value": 4000,
      "percentage": 3.4
    }
  ],
  "preventionDuty": 118000,
  "reliefDuty": 206000,
  "mainDuty": 97000,
  "householdsWithChildren": 47000,
  "timeSeries": [
    {
      "date": "2018-Q1",
      "value": 68000
    },
    {
      "date": "2019-Q1",
      "value": 74000
    },
    {
      "date": "2020-Q1",
      "value": 75000
    },
    {
      "date": "2021-Q1",
      "value": 69000
    },
    {
      "date": "2022-Q1",
      "value": 74000
    },
    {
      "date": "2023-Q1",
      "value": 95000
    },
    {
      "date": "2024-Q1",
      "value": 109000
    },
    {
      "date": "2024-Q3",
      "value": 117000
    }
  ],
  "roughSleepingTimeSeries": [
    {
      "date": "2019",
      "value": 4677
    },
    {
      "date": "2020",
      "value": 2688
    },
    {
      "date": "2021",
      "value": 2440
    },
    {
      "date": "2022",
      "value": 2723
    },
    {
      "date": "2023",
      "value": 3898
    },
    {
      "date": "2024",
      "value": 4389
    }
  ],
  "source": {
    "name": "DLUHC Homelessness Statistics",
    "url": "https://www.gov.uk/government/collections/homelessness-statistics",
    "releaseDate": "December 2024"
  }
} as const;
