// Auto-generated on 2026-04-15T04:49:48.211Z
// DO NOT EDIT MANUALLY - This file is generated by scripts/fetch-data.ts

export const nhsWelfareOverlap = {
  "mentalHealth": {
    "pipClaimantsWithMHCondition": 1340000,
    "asPercentageOfPIPCaseload": 36.5,
    "esaClaimantsWithMHCondition": 680000,
    "ucLimitedCapabilityWithMHCondition": 920000,
    "estimatedTotal": 2940000
  },
  "longTermSick": {
    "economicallyInactive": 2850000,
    "increaseSince2020": 650000,
    "receivingESAorUC": 2150000,
    "notReceivingBenefits": 700000
  },
  "nhsWaitingListImpact": {
    "estimatedOnBenefitsWhileWaiting": 450000,
    "averageWaitWeeks": 14
  },
  "byCondition": [
    {
      "category": "Depression",
      "value": 850000
    },
    {
      "category": "Anxiety disorders",
      "value": 620000
    },
    {
      "category": "Other psychiatric disorders",
      "value": 570000
    },
    {
      "category": "Psychosis",
      "value": 120000
    },
    {
      "category": "Personality disorders",
      "value": 85000
    },
    {
      "category": "Other",
      "value": 695000
    }
  ],
  "source": {
    "name": "ONS Labour Force Survey & DWP",
    "url": "https://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/unemployment",
    "releaseDate": "November 2024"
  }
} as const;
