// Auto-generated on 2026-05-15T05:59:17.894Z
// DO NOT EDIT MANUALLY - This file is generated by scripts/fetch-data.ts

export const pip = {
  "totalCaseload": 3670000,
  "changeYoY": 6.8,
  "newClaims": 270000,
  "clearances": 310000,
  "averageAward": 69.85,
  "byCondition": [
    {
      "category": "Psychiatric disorders",
      "value": 1340000,
      "percentage": 36.5
    },
    {
      "category": "Musculoskeletal disease (general)",
      "value": 520000,
      "percentage": 14.2
    },
    {
      "category": "Neurological disease",
      "value": 380000,
      "percentage": 10.4
    },
    {
      "category": "Musculoskeletal disease (regional)",
      "value": 290000,
      "percentage": 7.9
    },
    {
      "category": "Respiratory disease",
      "value": 180000,
      "percentage": 4.9
    },
    {
      "category": "Cardiovascular disease",
      "value": 150000,
      "percentage": 4.1
    },
    {
      "category": "Endocrine disease",
      "value": 140000,
      "percentage": 3.8
    },
    {
      "category": "Visual disease",
      "value": 120000,
      "percentage": 3.3
    },
    {
      "category": "Hearing disorders",
      "value": 90000,
      "percentage": 2.5
    },
    {
      "category": "Other",
      "value": 460000,
      "percentage": 12.4
    }
  ],
  "byAge": [
    {
      "category": "16-24",
      "value": 210000,
      "percentage": 5.7
    },
    {
      "category": "25-34",
      "value": 520000,
      "percentage": 14.2
    },
    {
      "category": "35-44",
      "value": 610000,
      "percentage": 16.6
    },
    {
      "category": "45-54",
      "value": 730000,
      "percentage": 19.9
    },
    {
      "category": "55-64",
      "value": 780000,
      "percentage": 21.3
    },
    {
      "category": "65-74",
      "value": 520000,
      "percentage": 14.2
    },
    {
      "category": "75+",
      "value": 300000,
      "percentage": 8.2
    }
  ],
  "byRegion": [
    {
      "region": "North East",
      "value": 250000,
      "percentage": 9.5
    },
    {
      "region": "North West",
      "value": 530000,
      "percentage": 7.2
    },
    {
      "region": "Yorkshire and Humber",
      "value": 340000,
      "percentage": 6.2
    },
    {
      "region": "East Midlands",
      "value": 280000,
      "percentage": 5.7
    },
    {
      "region": "West Midlands",
      "value": 370000,
      "percentage": 6.2
    },
    {
      "region": "East of England",
      "value": 310000,
      "percentage": 4.8
    },
    {
      "region": "London",
      "value": 360000,
      "percentage": 4
    },
    {
      "region": "South East",
      "value": 470000,
      "percentage": 5
    },
    {
      "region": "South West",
      "value": 340000,
      "percentage": 5.9
    },
    {
      "region": "Wales",
      "value": 260000,
      "percentage": 8.2
    },
    {
      "region": "Scotland",
      "value": 420000,
      "percentage": 7.9
    },
    {
      "region": "Northern Ireland",
      "value": 150000,
      "percentage": 7.9
    }
  ],
  "byComponent": [
    {
      "category": "Daily living only",
      "value": 480000,
      "percentage": 13.1
    },
    {
      "category": "Mobility only",
      "value": 310000,
      "percentage": 8.4
    },
    {
      "category": "Both components",
      "value": 2880000,
      "percentage": 78.5
    }
  ],
  "timeSeries": [
    {
      "date": "2019-04",
      "value": 2100000
    },
    {
      "date": "2020-04",
      "value": 2400000
    },
    {
      "date": "2021-04",
      "value": 2650000
    },
    {
      "date": "2022-04",
      "value": 2900000
    },
    {
      "date": "2023-04",
      "value": 3300000
    },
    {
      "date": "2024-04",
      "value": 3670000
    }
  ],
  "source": {
    "name": "DWP PIP Statistics",
    "url": "https://www.gov.uk/government/collections/personal-independence-payment-pip-statistics",
    "releaseDate": "November 2024"
  }
} as const;
