// Auto-generated on 2026-06-15T07:27:19.151Z
// DO NOT EDIT MANUALLY - This file is generated by scripts/fetch-data.ts

export const poverty = {
  "relativePovertyBHC": 11,
  "relativePovertyAHC": 14.5,
  "absolutePovertyBHC": 8.9,
  "absolutePovertyAHC": 11.4,
  "childrenInPoverty": 4.3,
  "pensionersInPoverty": 2.1,
  "workingAgeAdultsInPoverty": 8.1,
  "percentageBHC": 16.8,
  "percentageAHC": 22,
  "byRegion": [
    {
      "region": "London",
      "value": 27,
      "note": "AHC"
    },
    {
      "region": "North East",
      "value": 24,
      "note": "AHC"
    },
    {
      "region": "West Midlands",
      "value": 23,
      "note": "AHC"
    },
    {
      "region": "Yorkshire and Humber",
      "value": 22,
      "note": "AHC"
    },
    {
      "region": "North West",
      "value": 22,
      "note": "AHC"
    },
    {
      "region": "East Midlands",
      "value": 21,
      "note": "AHC"
    },
    {
      "region": "South West",
      "value": 19,
      "note": "AHC"
    },
    {
      "region": "South East",
      "value": 18,
      "note": "AHC"
    },
    {
      "region": "East of England",
      "value": 18,
      "note": "AHC"
    },
    {
      "region": "Scotland",
      "value": 21,
      "note": "AHC"
    },
    {
      "region": "Wales",
      "value": 22,
      "note": "AHC"
    },
    {
      "region": "Northern Ireland",
      "value": 18,
      "note": "AHC"
    }
  ],
  "byHouseholdType": [
    {
      "category": "Single working-age adult without children",
      "value": 30,
      "note": "AHC"
    },
    {
      "category": "Single working-age adult with children",
      "value": 48,
      "note": "AHC"
    },
    {
      "category": "Couple with children",
      "value": 25,
      "note": "AHC"
    },
    {
      "category": "Couple without children",
      "value": 11,
      "note": "AHC"
    },
    {
      "category": "Single pensioner",
      "value": 22,
      "note": "AHC"
    },
    {
      "category": "Couple pensioner",
      "value": 14,
      "note": "AHC"
    }
  ],
  "byEthnicity": [
    {
      "category": "White",
      "value": 18,
      "note": "AHC"
    },
    {
      "category": "Mixed",
      "value": 30,
      "note": "AHC"
    },
    {
      "category": "Indian",
      "value": 18,
      "note": "AHC"
    },
    {
      "category": "Pakistani/Bangladeshi",
      "value": 46,
      "note": "AHC"
    },
    {
      "category": "Black",
      "value": 38,
      "note": "AHC"
    },
    {
      "category": "Other",
      "value": 35,
      "note": "AHC"
    }
  ],
  "byDisabilityStatus": [
    {
      "category": "Someone disabled in family",
      "value": 27,
      "note": "AHC"
    },
    {
      "category": "No one disabled in family",
      "value": 19,
      "note": "AHC"
    }
  ],
  "materialDeprivation": {
    "children": 3.6,
    "pensioners": 1.2
  },
  "destitutionEstimate": 3.8,
  "foodBankUse": {
    "totalTrussellTrust": 3.1,
    "independentFoodBanks": 1.2
  },
  "timeSeries": [
    {
      "date": "2010-11",
      "value": 13.3,
      "note": "AHC millions"
    },
    {
      "date": "2015-16",
      "value": 13.9,
      "note": "AHC millions"
    },
    {
      "date": "2019-20",
      "value": 14.5,
      "note": "AHC millions"
    },
    {
      "date": "2020-21",
      "value": 13.4,
      "note": "AHC millions"
    },
    {
      "date": "2021-22",
      "value": 14,
      "note": "AHC millions"
    },
    {
      "date": "2022-23",
      "value": 14.5,
      "note": "AHC millions"
    }
  ],
  "source": {
    "name": "DWP Households Below Average Income",
    "url": "https://www.gov.uk/government/collections/households-below-average-income-hbai--2",
    "releaseDate": "March 2024 (FY 2022-23)"
  }
} as const;
