// Auto-generated on 2026-03-16T11:45:21.857Z
// DO NOT EDIT MANUALLY - This file is generated by scripts/fetch-data.ts

export const sources = {
  "lastUpdated": "2026-03-16T11:45:21.857Z",
  "sources": [
    {
      "name": "Department for Work and Pensions (DWP)",
      "url": "https://www.gov.uk/government/organisations/department-for-work-pensions/about/statistics"
    },
    {
      "name": "Home Office Immigration Statistics",
      "url": "https://www.gov.uk/government/statistical-data-sets/immigration-system-statistics-data-tables"
    },
    {
      "name": "Office for National Statistics (ONS)",
      "url": "https://www.ons.gov.uk/"
    },
    {
      "name": "Department of Health and Social Care (DHSC)",
      "url": "https://www.gov.uk/government/collections/adult-social-care-statistics"
    },
    {
      "name": "HM Revenue and Customs (HMRC)",
      "url": "https://www.gov.uk/government/collections/child-benefit-statistics"
    },
    {
      "name": "Department for Levelling Up, Housing and Communities",
      "url": "https://www.gov.uk/government/collections/homelessness-statistics"
    },
    {
      "name": "Social Security Scotland",
      "url": "https://www.socialsecurity.gov.scot/about-statistics"
    },
    {
      "name": "Joseph Rowntree Foundation",
      "url": "https://www.jrf.org.uk/"
    },
    {
      "name": "Trussell Trust",
      "url": "https://www.trusselltrust.org/"
    }
  ]
} as const;
