// Auto-generated on 2026-05-02T05:15:49.823Z
// DO NOT EDIT MANUALLY - This file is generated by scripts/fetch-data.ts

export const statePension = {
  "totalRecipients": 12.6,
  "newStatePension": 8.4,
  "basicStatePension": 4.2,
  "averageWeeklyAmount": 192.45,
  "byAge": [
    {
      "category": "66-70",
      "value": 3600000,
      "percentage": 28.6
    },
    {
      "category": "71-75",
      "value": 2800000,
      "percentage": 22.2
    },
    {
      "category": "76-80",
      "value": 2500000,
      "percentage": 19.8
    },
    {
      "category": "81-85",
      "value": 2100000,
      "percentage": 16.7
    },
    {
      "category": "86+",
      "value": 1600000,
      "percentage": 12.7
    }
  ],
  "byGender": [
    {
      "category": "Male",
      "value": 5400000,
      "percentage": 42.9
    },
    {
      "category": "Female",
      "value": 7200000,
      "percentage": 57.1
    }
  ],
  "expenditure": 125000000000,
  "tripleLockUplift": 8.5,
  "timeSeries": [
    {
      "date": "2019",
      "value": 12.2,
      "note": "million"
    },
    {
      "date": "2020",
      "value": 12.3,
      "note": "million"
    },
    {
      "date": "2021",
      "value": 12.4,
      "note": "million"
    },
    {
      "date": "2022",
      "value": 12.4,
      "note": "million"
    },
    {
      "date": "2023",
      "value": 12.5,
      "note": "million"
    },
    {
      "date": "2024",
      "value": 12.6,
      "note": "million"
    }
  ],
  "source": {
    "name": "DWP State Pension Statistics",
    "url": "https://www.gov.uk/government/collections/state-pension-statistics",
    "releaseDate": "November 2024"
  }
} as const;
