// Auto-generated on 2026-07-01T06:38:44.902Z
// DO NOT EDIT MANUALLY - This file is generated by scripts/fetch-data.ts

export const universalCredit = {
  "totalCaseload": 6420000,
  "changeYoY": 2.3,
  "searchWork": 1810000,
  "workFocusedInterview": 156000,
  "workPreparation": 1230000,
  "workingWithRequirements": 430000,
  "noWorkRequirements": 2790000,
  "byRegion": [
    {
      "region": "London",
      "value": 950000,
      "percentage": 14.8
    },
    {
      "region": "North West",
      "value": 810000,
      "percentage": 12.6
    },
    {
      "region": "South East",
      "value": 780000,
      "percentage": 12.1
    },
    {
      "region": "Yorkshire and Humber",
      "value": 560000,
      "percentage": 8.7
    },
    {
      "region": "West Midlands",
      "value": 540000,
      "percentage": 8.4
    },
    {
      "region": "East of England",
      "value": 480000,
      "percentage": 7.5
    },
    {
      "region": "North East",
      "value": 340000,
      "percentage": 5.3
    },
    {
      "region": "South West",
      "value": 420000,
      "percentage": 6.5
    },
    {
      "region": "East Midlands",
      "value": 380000,
      "percentage": 5.9
    },
    {
      "region": "Scotland",
      "value": 530000,
      "percentage": 8.3
    },
    {
      "region": "Wales",
      "value": 280000,
      "percentage": 4.4
    },
    {
      "region": "Northern Ireland",
      "value": 230000,
      "percentage": 3.6
    }
  ],
  "byAge": [
    {
      "category": "18-24",
      "value": 880000,
      "percentage": 13.7
    },
    {
      "category": "25-34",
      "value": 1500000,
      "percentage": 23.4
    },
    {
      "category": "35-44",
      "value": 1400000,
      "percentage": 21.8
    },
    {
      "category": "45-54",
      "value": 1300000,
      "percentage": 20.2
    },
    {
      "category": "55-64",
      "value": 1040000,
      "percentage": 16.2
    },
    {
      "category": "65+",
      "value": 300000,
      "percentage": 4.7
    }
  ],
  "byGender": [
    {
      "category": "Male",
      "value": 3200000,
      "percentage": 49.8
    },
    {
      "category": "Female",
      "value": 3220000,
      "percentage": 50.2
    }
  ],
  "expenditure": 95000000000,
  "averageAward": 380,
  "timeSeries": [
    {
      "date": "2019-01",
      "value": 1500000
    },
    {
      "date": "2019-07",
      "value": 1800000
    },
    {
      "date": "2020-01",
      "value": 2600000
    },
    {
      "date": "2020-07",
      "value": 5700000
    },
    {
      "date": "2021-01",
      "value": 5900000
    },
    {
      "date": "2021-07",
      "value": 5400000
    },
    {
      "date": "2022-01",
      "value": 5200000
    },
    {
      "date": "2022-07",
      "value": 5500000
    },
    {
      "date": "2023-01",
      "value": 5900000
    },
    {
      "date": "2023-07",
      "value": 6100000
    },
    {
      "date": "2024-01",
      "value": 6250000
    },
    {
      "date": "2024-07",
      "value": 6420000
    }
  ],
  "source": {
    "name": "DWP Universal Credit Statistics",
    "url": "https://www.gov.uk/government/collections/universal-credit-statistics",
    "releaseDate": "November 2024"
  }
} as const;
